### ISSUE TITLE
현진님 서버와 통신시 예약 조회 오류

### ISSUE THREAD

**Issue by JeongHyeon2** [kumoh42/futsal-front#14]
배포된 서버 - flutter windows, chrome 으로 실행시 정상적으로 작동 됨

현진님 서버 - flutter chrome 으로 실행시 access token, refersh token이 null로 응답이 옴.

현진님 서버 - flutter windows로 실행시 아래의 에러
1. 7월 예약 조회시 빈 Container
![image](https://github.com/kumoh42/futsal-front/assets/81457699/07735767-9d4c-4bbc-8bb3-edb5681c7854)

2. 8월 1일 예약 조회시 
![image](https://github.com/kumoh42/futsal-front/assets/81457699/ad969378-6313-4da1-9921-3dbb6d5595ea)

3. 2023년 6월 이전의 데이터들이 빈 값으로 들어와서
예약이 시작되지 않았습니다. 라고 뜸

**Comment by qkrwnstlr** [comment]
아마 cors관련 에러로 보입니다.
혹시 ngrok 관련 header 설정 하셨나요?
ngrok 사용할때는 요청에 전용 헤더를 추가해줘야합니다.

dio options에 다음 코드를 추가해보세요.
```
headers: {'ngrok-skip-browser-warning' : true}
```

**Comment by JeongHyeon2** [comment]
아하!! 알겠습니다. ngrok으로 연결 할 때는 저 코드 넣어줘야하는거군요!

**Comment by qkrwnstlr** [comment]
네! ngrok하고 테스트 할때만 필요한거니까 테스트 마치고 pr 날릴때는 제거해주세요!

**Comment by gimseonjin** [comment]
<img width="1728" alt="image" src="https://github.com/kumoh42/futsal-front/assets/66009926/67e2d48e-a83f-4f39-8a47-7d52e9a44562">

main.ts에 이 코드 안넣어줘서 그런드듯 하네요
